version: '2'
services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "gitlab"
    ports:
      - "10443:443"
      - "10080:10080"
      - "2222:22"
    volumes:
      - "/data/gitlab/config:/etc/gitlab"
      - "/data/gitlab/logs:/var/log/gitlab"
      - "/data/gitlab/data:/var/opt/gitlab"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.210:10080'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222