version: "2"
services:
  mysql1:
    container_name: "mysql1"
    image: mysql:latest
    volumes:
      - ./mysql1:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    restart: always

  mysql2:
    container_name: "mysql2"
    image: mysql:latest
    volumes:
      - ./mysql2:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    restart: always

  mysql3:
    container_name: "mysql3"
    image: mysql:latest
    volumes:
      - ./mysql3:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    restart: always