version: '2'
services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.4.0"
    hostname: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
    depends_on:
      - elasticsearch
