version: '2'

services:
  logspout:
    container_name: logspout
    image: 'gliderlabs/logspout:latest'
    ports:
      - '81:80'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock